#ifndef INC_KLST_PANDA_CONFIG_H_
#define INC_KLST_PANDA_CONFIG_H_

#define KLST_PANDA_ENABLE_GPIO
#define KLST_PANDA_ENABLE_SERIAL_DEBUG
#define KLST_PANDA_ENABLE_EXTERNAL_MEMORY
#define KLST_PANDA_ENABLE_DISPLAY
//#define KLST_PANDA_ENABLE_AUDIOCODEC
//#define KLST_PANDA_ENABLE_ON_BOARD_MIC
//#define KLST_PANDA_ENABLE_ENCODER
//#define KLST_PANDA_ENABLE_SD_CARD
#define KLST_PANDA_ENABLE_IDC_SERIAL
#define KLST_PANDA_ENABLE_MIDI
//#define KLST_PANDA_ENABLE_MECHANICAL_KEYS
//#define KLST_PANDA_ENABLE_USB_HOST
//#define KLST_PANDA_ENABLE_USB_DEVICE

#endif /* INC_KLST_PANDA_CONFIG_H_ */
