#ifndef INC_KLST_PANDA_CONFIG_H_
#define INC_KLST_PANDA_CONFIG_H_

#define KLST_PANDA_ENABLE_GPIO
#define KLST_PANDA_ENABLE_SERIAL_DEBUG
#define KLST_PANDA_ENABLE_EXTERNAL_MEMORY
#define KLST_PANDA_ENABLE_DISPLAY
//#define KLST_PANDA_ENABLE_AUDIOCODEC
//#define KLST_PANDA_ENABLE_ON_BOARD_MIC
#define KLST_PANDA_ENABLE_ENCODER
//#define KLST_PANDA_ENABLE_SD_CARD
#define KLST_PANDA_ENABLE_IDC_SERIAL

#endif /* INC_KLST_PANDA_CONFIG_H_ */
